package lotto.global

const val LOTTO_PRICE = 1_000
const val LOTTO_MINIMUM_AMOUNT = 1_000
const val LOTTO_MAXIMUM_AMOUNT = "1000000"
const val LOTTO_MAXIMUM_AMOUNT_LENGTH = 7
const val LOTTO_MINIMUM_NUMBER = 1
const val LOTTO_MAXIMUM_NUMBER = 45
const val LOTTO_NUMBERS_SIZE = 6
